name: Construire mon APK Android

on:
  workflow_dispatch:

jobs:
  build:
    name: Compiler l'application Android
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Installer Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Installer Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      - name: Compiler l'APK
        run: gradle assembleDebug

      - name: Récupérer l'APK
        uses: actions/upload-artifact@v4
        with:
          name: Jenkil-APK
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
